### ISSUE TITLE
No release file

### ISSUE THREAD

**Issue by grahfmusic** [Lyall/HundredHeroesFix#1]
Hi,

Just wondering if there is reason there is release zip.  I really want to use this on Linux :)

**Comment by Lyall** [comment]
Sorry, I spotted a few issues after making the repo public, so I should have a release out later today. I'll post an update to this issue when it's out!

**Comment by Lyall** [comment]
That's the first [release out now](https://github.com/Lyall/HundredHeroesFix/releases). Feel free to create an issue if you run in to any problems or spot any bugs!

**Comment by grahfmusic** [comment]
Thank you, it works wonderfully under Proton.
