### ISSUE TITLE
WallScrolls/Trading

### ISSUE THREAD

**Issue by Duradan** [Lyall/HundredHeroesFix#12]
Loaded your mod in, trading menu/wallscrolls stop showing up.
unistalled your mod, They returned

only your mod was installed

**Comment by Lyall** [comment]
Can you post your `LogOutput.log` file from the BepInEx folder?

**Comment by Duradan** [comment]
[Message: Preloader] BepInEx 6.0.0-be.688 - EiyudenChronicle
[Message: Preloader] Built from commit 49015217f3becf052d33fa4658ac19229f5daa3a
[Info   :   BepInEx] System platform: Windows 10 64-bit
[Info   :   BepInEx] Process bitness: 64-bit (x64)
[Info   :   BepInEx] Running under Unity 2021.3.32f1
[Info   :   BepInEx] Runtime version: 6.0.7
[Info   :   BepInEx] Runtime information: .NET 6.0.7
[Message:InteropManager] Downloading unity base libraries
[Message:InteropManager] Extracting downloaded unity base libraries
[Message:InteropManager] Running Cpp2IL to generate dummy assemblies
[Info   :    Cpp2IL] [Library] Initializing Metadata...
[Info   :    Cpp2IL] [Library] Using actual IL2CPP Metadata version 29
[Info   :    Cpp2IL] [Library] Initialized Metadata in 341ms
[Info   :    Cpp2IL] [Library] Using binary type Portable Executable (from LibCpp2IL)
[Info   :    Cpp2IL] [Library] Searching Binary for Required Data...
[Info   :    Cpp2IL] [Library] Got Binary codereg: 0x183AA7140, metareg: 0x1843EF9E0 in 151ms.
[Info   :    Cpp2IL] [Library] Initializing Binary...
[Info   :    Cpp2IL] [Library] Initialized Binary in 235ms
[Info   :    Cpp2IL] [Library] Mapping pointers to Il2CppMethodDefinitions...
[Info   :    Cpp2IL] [Library] Processed 163745 OK (135ms)
[Info   :    Cpp2IL] [Program] Creating application model...
[Info   :    Cpp2IL] [Program] Application model created in 1701.7122ms
[Info   :InteropManager] Cpp2IL finished in 00:00:10.9437165
[Info   :InteropManager] Generating interop assemblies
[Info   :Il2CppInteropGen] Reading assemblies...
[Info   :Il2CppInteropGen] Done in 00:00:00.0521548
[Info   :Il2CppInteropGen] Reading unity assemblies...
[Info   :Il2CppInteropGen] Done in 00:00:00.0080413
[Info   :Il2CppInteropGen] Creating rewrite assemblies...
[Info   :Il2CppInteropGen] Done in 00:00:00.0097805
[Info   :Il2CppInteropGen] Computing renames...
[Info   :Il2CppInteropGen] Done in 00:00:00.0574988
[Info   :Il2CppInteropGen] Creating typedefs...
[Info   :Il2CppInteropGen] Done in 00:00:00.0763242
[Info   :Il2CppInteropGen] Computing struct blittability...
[Info   :Il2CppInteropGen] Done in 00:00:00.0788488
[Info   :Il2CppInteropGen] Filling typedefs...
[Info   :Il2CppInteropGen] Done in 00:00:00.0620340
[Info   :Il2CppInteropGen] Filling generic constraints...
[Info   :Il2CppInteropGen] Done in 00:00:00.0056402
[Info   :Il2CppInteropGen] Creating members...
[Info   :Il2CppInteropGen] Done in 00:00:01.8937886
[Info   :Il2CppInteropGen] Scanning method cross-references...
[Info   :Il2CppInteropGen] Done in 00:00:01.1163335
[Info   :Il2CppInteropGen] Finalizing method declarations...
[Info   :Il2CppInteropGen] Done in 00:00:02.6245890
[Info   :Il2CppInteropGen] 167 total potentially dead methods
[Info   :Il2CppInteropGen] Filling method parameters...
[Info   :Il2CppInteropGen] Done in 00:00:00.5475737
[Info   :Il2CppInteropGen] Creating static constructors...
[Info   :Il2CppInteropGen] Done in 00:00:00.8094322
[Info   :Il2CppInteropGen] Creating value type fields...
[Info   :Il2CppInteropGen] Done in 00:00:00.0567304
[Info   :Il2CppInteropGen] Creating enums...
[Info   :Il2CppInteropGen] Done in 00:00:00.0611718
[Info   :Il2CppInteropGen] Creating IntPtr constructors...
[Info   :Il2CppInteropGen] Done in 00:00:00.2870059
[Info   :Il2CppInteropGen] Creating non-blittable struct constructors...
[Info   :Il2CppInteropGen] Done in 00:00:00.0265606
[Info   :Il2CppInteropGen] Creating generic method static constructors...
[Info   :Il2CppInteropGen] Done in 00:00:00.1050643
[Info   :Il2CppInteropGen] Creating field accessors...
[Info   :Il2CppInteropGen] Done in 00:00:02.5579740
[Info   :Il2CppInteropGen] Filling methods...
[Info   :Il2CppInteropGen] Done in 00:00:05.7521920
[Info   :Il2CppInteropGen] Generating implicit conversions...
[Info   :Il2CppInteropGen] Done in 00:00:00.0235624
[Info   :Il2CppInteropGen] Creating properties...
[Info   :Il2CppInteropGen] Done in 00:00:00.1821985
[Info   :Il2CppInteropGen] Unstripping types...
[Info   :Il2CppInteropGen] Done in 00:00:00.0354391
[Info   :Il2CppInteropGen] Unstripping fields...
[Info   :Il2CppInteropGen] Restored 278 fields
[Info   :Il2CppInteropGen] Failed to restore 0 fields
[Info   :Il2CppInteropGen] Done in 00:00:00.0069660
[Info   :Il2CppInteropGen] Unstripping methods...
[Info   :Il2CppInteropGen] Restored 11232 methods
[Info   :Il2CppInteropGen] Failed to restore 753 methods
[Info   :Il2CppInteropGen] Done in 00:00:00.2628816
[Info   :Il2CppInteropGen] Unstripping method bodies...
[Info   :Il2CppInteropGen] IL unstrip statistics: 5924 successful, 1642 failed
[Info   :Il2CppInteropGen] Done in 00:00:00.2615604
[Info   :Il2CppInteropGen] Writing xref cache...
[Info   :Il2CppInteropGen] Done in 00:00:03.8032365
[Info   :Il2CppInteropGen] Writing assemblies...
[Info   :Il2CppInteropGen] Done in 00:00:01.6428166
[Info   :Il2CppInteropGen] Writing method pointer map...
[Info   :Il2CppInteropGen] Done in 00:00:00.0502077
[Info   :Il2CppInteropGen] Done!
[Info   : Preloader] 0 patcher plugins loaded
[Info   : Preloader] 0 assemblies discovered
[Message:AssemblyPatcher] Executing 0 patch(es)
[Message:   BepInEx] Chainloader initialized
[Warning:Il2CppInterop] Class::Init signatures have been exhausted, using a substitute!
[Info   :Il2CppInterop] Registered mono type Il2CppInterop.Runtime.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain
[Info   :   BepInEx] 1 plugin to load
[Info   :   BepInEx] Loading [HundredHeroesFix 0.9.2]
[Info   :HundredHeroesFix] Plugin HundredHeroesFix is loaded!
[Info   :HundredHeroesFix] Patches: Applying resolution patch.
[Info   :HundredHeroesFix] Patches: Applying miscellaneous patch.
[Info   :HundredHeroesFix] Patches: Applying skip intro patch.
[Info   :HundredHeroesFix] Disabled mouse cursor visibility.
[Message:   BepInEx] Chainloader startup complete
[Info   :HundredHeroesFix] Resolution: Applied custom resolution of 3840x2160 : Fullscreen = True
[Info   :HundredHeroesFix] Resolution: Applied custom resolution of 3840x2160 : Fullscreen = True
[Info   :HundredHeroesFix] Intro Skip: Enabled skippable logos.
[Info   :HundredHeroesFix] Intro Skip: Skipping intro logos.
[Info   :HundredHeroesFix] Intro Skip: Skipping intro logos.
[Info   :HundredHeroesFix] Intro Skip: Skipped opening movie.
[Info   :HundredHeroesFix] Resolution: Applied custom resolution of 3840x2160 : Fullscreen = True
[Info   :HundredHeroesFix] Resolution: Applied custom resolution of 3840x2160 : Fullscreen = True
[Info   :HundredHeroesFix] Resolution: Applied custom resolution of 3840x2160 : Fullscreen = True
[Info   :HundredHeroesFix] Resolution: Applied custom resolution of 3840x2160 : Fullscreen = True
[Info   :HundredHeroesFix] Resolution: Applied custom resolution of 3840x2160 : Fullscreen = True
[Info   :HundredHeroesFix] Resolution: Applied custom resolution of 3840x2160 : Fullscreen = True
[Info   :HundredHeroesFix] Resolution: Applied custom resolution of 3840x2160 : Fullscreen = True
[Info   :HundredHeroesFix] Intro Skip: Enabled skippable logos.
[Info   :HundredHeroesFix] Intro Skip: Skipping intro logos.
[Info   :HundredHeroesFix] Intro Skip: Skipping intro logos.

**Comment by Duradan** [comment]
Nevermind, this is an actual game bug, I think. it fixed it self after i removed your mod, but when i put you mod back it, it works correctly, Ill just go report the atcual bug to R&B
