### ISSUE TITLE
Question: Possible to modify Z-Depth buffer?

### ISSUE THREAD

**Issue by shinra358** [Lyall/HundredHeroesFix#15]
Is it possible with Bep to modify the z depth buffer offset of hud elements and text?

**Comment by Lyall** [comment]
Why would you want to change the z-depth of UI elements? The UI in this game is 2D anyway.

**Comment by shinra358** [comment]
for 3dvision and other stereoscopic methods, i have unlocked depth in reshade and the ui elements zdepth is at the 'back of the room' and needs to be brought forth to the front so that 3d looks correct.

and for 2D, i have modified some reshade shaders to display on a user defined depth and if the ui elements can be brought forth zdepth wise, it'll allow the shaders to be used without affecting the ui (more advanced than just using uimasks).

yes i know the ui elements are 2d.

**Comment by Lyall** [comment]
That kind of thing would be out of the scope of what this mod is for I'm afraid.
