### ISSUE TITLE
[0.9.7] System.Net.Http.HttpRequestException

### ISSUE THREAD

**Issue by Nyankoo** [Lyall/HundredHeroesFix#18]
When trying to start the game (v1.0.3), nothing happens and the LogOutput has the following error:

`Failed to generate Il2Cpp interop assemblies: System.Net.Http.HttpRequestException: Access to a socket was not permitted due to the access rights of the socket. (unity.bepinex.dev:443)`

I dropped the files in the main game folder, but did I maybe miss something?

**Comment by Lyall** [comment]
Sounds like BepInEx is failing to connect to the server that has the Unity libs on it. Do you have a restrictive firewall setup or are you using a VPN or anything? I'd suggest trying anything you'd normally troubleshoot for internet connection issues. Also you could try launching the game as an admin too.

**Comment by Nyankoo** [comment]
@Lyall It was indeed a firewall issue. Thank you for your quick help and I'm sorry for the false alarm!
