### ISSUE TITLE
cat shadow + others?

### ISSUE THREAD

**Issue by porkbob** [Lyall/HundredHeroesFix#3]
The new version looks amazing. I didn't have long to run around and check things, but the little I was able to I noticed this behavior for the cat in the southwest corner of Eltisweiss; Specifically only when it lies down, the shadow supercedes the sprite to be on top.

![EiyudenChronicle_juZnp9iDv6](https://github.com/Lyall/HundredHeroesFix/assets/23653103/5d1079ef-6f11-4b2c-9e1b-48f6ec54145f)

No idea if there are any other instances of this sort of thing happening. And if there isn't anything that can be done about it, then no worries, just close the issue.

In case it is relevant or helps, here is my config. (Had to rename it to .txt in order to attach.)
[HundredHeroesFix.txt](https://github.com/Lyall/HundredHeroesFix/files/15125395/HundredHeroesFix.txt)

**Comment by Lyall** [comment]
I see what you mean. Testing it out in-game it looks like it's even an issue at the stock graphical settings, though it's highlighted even more with higher shadow settings. I think it might just be an issue with the cascaded shadow map approach and the shadow caster being a billboard (2D). I'm not exactly sure on what could be done to solve it. Altering the shadow depth bias helps a little but you lose detail in other shadows so there doesn't appear to be a clear cut fix I'm afraid.

**Comment by Lyall** [comment]
Don't think there's anything I can do mod-wise to address this so I'm going to close this issue for now.
