### ISSUE TITLE
Become More Slower when enable the tweak

### ISSUE THREAD

**Issue by ShadeRedeye** [Lyall/HundredHeroesFix#4]
so i found these mod for sake playing this game in my low end laptop
my spec : 
AMD A8-7410 (4 cpu)
AMD radeon R5
RAM 8gb
Windows 10
but instead it just become slower(in menu i got 10 or lower fps and outdoor i almost got freeze ).
when i set it to false,it become normal.

I look the Log but it seems pretty normal

`[Message: Preloader] BepInEx 6.0.0-be.688 - EiyudenChronicle
[Message: Preloader] Built from commit 49015217f3becf052d33fa4658ac19229f5daa3a
[Info   :   BepInEx] System platform: Windows 10 64-bit
[Info   :   BepInEx] Process bitness: 64-bit (x64)
[Info   :   BepInEx] Running under Unity 2021.3.32f1
[Info   :   BepInEx] Runtime version: 6.0.7
[Info   :   BepInEx] Runtime information: .NET 6.0.7
[Info   : Preloader] 0 patcher plugins loaded
[Info   : Preloader] 0 assemblies discovered
[Message:AssemblyPatcher] Executing 0 patch(es)
[Message:   BepInEx] Chainloader initialized
[Warning:Il2CppInterop] Class::Init signatures have been exhausted, using a substitute!
[Info   :Il2CppInterop] Registered mono type Il2CppInterop.Runtime.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain
[Info   :   BepInEx] 1 plugin to load
[Info   :   BepInEx] Loading [HundredHeroesFix 0.9.0]
[Info   :HundredHeroesFix] Plugin HundredHeroesFix is loaded!
[Info   :HundredHeroesFix] Disabled mouse cursor visibility.
[Message:   BepInEx] Chainloader startup complete
[Info   :HundredHeroesFix] Scaled fade.
[Info   :HundredHeroesFix] Applied custom resolution of 1366x768 : Fullscreen = True
[Info   :HundredHeroesFix] Applied custom resolution of 1366x768 : Fullscreen = True
[Info   :HundredHeroesFix] Skipping intro logos.
[Info   :HundredHeroesFix] Skipping intro logos.
[Info   :HundredHeroesFix] Skipped opening movie.
[Info   :HundredHeroesFix] Fixed broken screen SaveLoadCanvas(Clone).
[Info   :HundredHeroesFix] Adjusted the size of ReSaveLoadCanvas->filter
[Info   :HundredHeroesFix] Adjusted the size of dialog->Filter
[Info   :HundredHeroesFix] Changed intestity of Post-processing Volume's vignette to 0,3998048
[Info   :HundredHeroesFix] Changed intestity of Sky and Fog Volume's vignette to 0,3998048
[Info   :HundredHeroesFix] Changed background colour of Main Camera.
[Info   :HundredHeroesFix] Changed background colour of Main Camera.
[Info   :HundredHeroesFix] Fixed broken screen Canvas.
[Info   :HundredHeroesFix] Adjusted the size of background blur
[Info   :HundredHeroesFix] Adjusted the size of SystemCanvas(Clone)->filter
[Info   :HundredHeroesFix] Adjusted the size of dialogSorting_systemMenu Variant->Filter
[Info   :HundredHeroesFix] Adjusted the size of OptionCanvas Variant->filter
[Info   :HundredHeroesFix] Adjusted the size of OptionCanvas->filter
[Info   :HundredHeroesFix] Skipping intro logos.
[Info   :HundredHeroesFix] Skipping intro logos.
[Info   :HundredHeroesFix] Adjusted the size of OptionCanvas->filter
[Info   :HundredHeroesFix] Applied custom resolution of 1366x768 : Fullscreen = True
[Info   :HundredHeroesFix] Applied custom resolution of 1366x768 : Fullscreen = True
[Info   :HundredHeroesFix] Applied custom resolution of 1366x768 : Fullscreen = True
[Info   :HundredHeroesFix] Applied custom resolution of 1366x768 : Fullscreen = True
`

using latest version one.

**Comment by porkbob** [comment]
This mod increases the graphics settings, so if you were already having performance issues or even on the edge of having them, it is expected that it will just require more graphical power. It is possible to lower them in the config file though, so if you only wanted something specific like custom resolution, you should be able to do that and get the original performance you had.

**Comment by ShadeRedeye** [comment]
i try lower all setting of it but it didn't work,try to set res to 800p,still slow (maybe it just only affect a display such ui not rendering one)

**Comment by shinra358** [comment]
Renderscale is what is doing it. And it is because they are rendering big areas. that's why they had the scale lower. Problem is, even when you overclock, it's the exact same fps. So adding anisotropic filtering with negative lod bias clamp will help with the shimmering at lower renderscales so one would have a clean picture without high resolution. for now, disable custom resolution, put shadows to 2048, renderscale to 4, smaa off and that should make it a bit faster with top quality. ingame 30fps and ingame rez 1080p

**Comment by Lyall** [comment]
Your specs are actually below the minimum specs to even run the game. Your CPU in particular (the A8-7410) scores 52pts in Cinebench R15 and the min spec calls for an i5-4670K which nets 550pts. Once you run BepInEx on top of this game, it's no wonder that your performance drops. There will be added CPU overhead in just running BepInEx and your CPU is already at its limit just trying to run the game.

I'm afraid there's not a lot you can do here. Unity in particular tends to be single-threaded which is an area where your CPU performs even worse.

**Comment by ShadeRedeye** [comment]
ah forget it,i just found out the problem,in render scale use dot "." instead of comma "," never though the comment in setting lend to stoopid input.since wrong input will change value to 4 (which mean 4x render resolution).

i got "playable" fps because of this solve.
