### ISSUE TITLE
Intro Skip Modification (button press skip instead)

### ISSUE THREAD

**Issue by shinra358** [Lyall/HundredHeroesFix#5]
when you are in-game and you choose the option to go back to the title screen, you are able to skip intro by pressing a button. You cannot skip intro with a button press on cold start. Can you make it so instead of skipping the intro completely, that you can be able to skip it on cold start with a button press instead like you can when you choose back to title?

**Comment by Lyall** [comment]
That's a good suggestion. I did see some references to an skippable intro option when creating the patches for this fix's intro skip feature but I wasn't able to get them to work. I'll look more in to this and see what can be done.

**Comment by Lyall** [comment]
Okay, in the next version I've added in a patch to enable the skippable flag that gets enabled after you've returned to the title menu. It's going to be enabled by default, even if you disable the skip intro stuff in the config since it doesn't actually skip it.
