### ISSUE TITLE
Window Mode Hotkey & Separate Sizing

### ISSUE THREAD

**Issue by shinra358** [Lyall/HundredHeroesFix#7]
Thank you for your work. I would like to be able to press Alt+Enter to go into window mode on the fly and would like an option to specify that window size once in window mode. This would be useful for single monitor ppl trying to view a guide elsewhere. Thx in advance.

**Comment by Lyall** [comment]
Both those options are Unity player settings which can't be changed during runtime unfortunately. It would theoretically be possible to enable window resizing through the use of Windows APIs but that's quite a bit of work. Sorry!
